name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with: { python-version: '3.11' }
    - name: Install backend deps
      working-directory: backend-fastapi
      run: pip install -r requirements.txt
    - name: Run backend tests
      working-directory: backend-fastapi
      run: pytest

  build-frontend:
    runs-on: ubuntu-latest
    needs: test-backend
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with: { node-version: '20' }
    - name: Install & build
      working-directory: frontend-react
      run: |
        npm ci
        npm run build
